spring:
  application:
    name: currencyExchangeRedo1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5491/currencyExchangeRedo1
    username: user
    password: password

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
