CREATE TABLE country
(
    country_id            BIGINT       NOT NULL,
    currency_id           BIGINT,
    country_name          VARCHAR(255) NOT NULL,
    currency_country_uses VARCHAR(255) NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (country_id)
);

CREATE TABLE currency_code
(
    currency_id   BIGINT       NOT NULL,
    currency_name VARCHAR(255) NOT NULL,
    currency_code VARCHAR(255) NOT NULL,
    CONSTRAINT pk_currency_code PRIMARY KEY (currency_id)
);

CREATE TABLE user_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_id    BIGINT,
    user_name     VARCHAR(255),
    user_password VARCHAR(255),
    date_of_birth date,
    CONSTRAINT pk_user_info PRIMARY KEY (id)
);

ALTER TABLE country
    ADD CONSTRAINT FK_COUNTRY_ON_CURRENCY FOREIGN KEY (currency_id) REFERENCES currency_code (currency_id);

ALTER TABLE user_info
    ADD CONSTRAINT FK_USER_INFO_ON_COUNTRYID FOREIGN KEY (country_id) REFERENCES country (country_id);