CREATE TABLE itinerary
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                           BIGINT,
    country_id                        BIGINT,
    order_on_trip                     INTEGER                                 NOT NULL,
    country_of_origin                 BOOLEAN,
    start_date                        date,
    end_date                          date,
    days_spent_in_country             INTEGER                                 NOT NULL,
    user_wants_currency_exchange_rate BOOLEAN,
    CONSTRAINT pk_itinerary PRIMARY KEY (id)
);

ALTER TABLE itinerary
    ADD CONSTRAINT FK_ITINERARY_ON_COUNTRYID FOREIGN KEY (country_id) REFERENCES country (country_id);

ALTER TABLE itinerary
    ADD CONSTRAINT FK_ITINERARY_ON_USERID FOREIGN KEY (user_id) REFERENCES user_info (id);